// Custom Next.js image loader — serves pre-generated responsive variants
// from /public/_responsive instead of depending on Vercel's paid image
// optimization API (which was disabled site-wide via `unoptimized: true`
// after hitting a 402/quota error, at the cost of all responsive srcset
// behavior). Variants are generated by scripts/generate-responsive-images.sh.
//
// Only local /public assets are handled here (this site has no remote
// images). Variant widths must match the WIDTHS array in that script.

const VARIANT_WIDTHS = [640, 828, 1080];

type LoaderParams = {
  src: string;
  width: number;
  quality?: number;
};

export default function imageLoader({ src, width }: LoaderParams): string {
  // External/absolute URLs pass through untouched.
  if (src.startsWith("http://") || src.startsWith("https://")) {
    return src;
  }

  const dotIndex = src.lastIndexOf(".");
  if (dotIndex === -1) return src;

  const base = src.slice(0, dotIndex); // "/website-blog-foo"
  const ext = src.slice(dotIndex); // ".webp"

  // Pick the smallest pre-generated variant that's still >= the requested
  // width; fall back to the full-size original for anything larger.
  const fit = VARIANT_WIDTHS.find((w) => w >= width);
  if (!fit) {
    return src; // original file already sized to ~1600-1920px max
  }

  return `${base.replace(/^\//, "/_responsive/")}-${fit}w${ext}`;
}
